language: rust
rust:
  - nightly
cache: cargo
script:
  - rustup component add rust-src
  - rustup component add llvm-tools-preview
  - cargo install cargo-xbuild
  - cargo install bootimage
  - cargo xbuild --verbose --all
  - cargo xtest --verbose --all
addons:
  apt:
    update: true
    packages:
    - qemu